In [4]:
pip install seaborn

Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (2.3.5)
Requirement already satisfied: pandas>=1.2 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (3.0.1)
Collecting matplotlib!=3.6.1,>=3.4 (from seaborn)
  Downloading matplotlib-3.10.8-cp311-cp311-win_amd64.whl.metadata (52 kB)
     ---------------------------------------- 0.0/52.8 kB ? eta -:--:--
     ------- -------------------------------- 10.2/52.8 kB ? eta -:--:--
     ------- -------------------------------- 10.2/52.8 kB ? eta -:--:--
     ------- -------------------------------- 10.2/52.8 kB ? eta -:--:--
     ------- -------------------------------- 10.2/52.8 kB ? eta -:--:--
     ------- -------------------------------- 10.2/52.8 kB ? eta -:--:--
     ------- -------------------------------- 10.2/52.8 kB ? eta -:--:--
     ------- -------------------------------- 10.2/52.8 kB ? eta -:--:--
     ------- -------------------------------- 10.2/52.8 kB ? eta -:--:--
     ------- -------------------------------- 10.2/52.8 kB ? eta -:--:--
     ------- -------------------------------- 10.2/52.8 kB ? eta -:--:--
     ------- -------------------------------- 10.2/52.8 kB ? eta -:--:--
     ------- -------------------------------- 10.2/52.8 kB ? eta -:--:--
     ------- -------------------------------- 10.2/52.8 kB ? eta -:--:--
     ------------------------------------- - 51.2/52.8 kB 65.5 kB/s eta 0:00:01
     --------------------------------------- 52.8/52.8 kB 64.9 kB/s eta 0:00:00
Collecting contourpy>=1.0.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading contourpy-1.3.3-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading fonttools-4.62.0-cp311-cp311-win_amd64.whl.metadata (119 kB)
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --- ------------------------------------ 10.2/119.6 kB ? eta -:--:--
     --------- ---------------------------- 30.7/119.6 kB 13.9 kB/s eta 0:00:07
     --------- ---------------------------- 30.7/119.6 kB 13.9 kB/s eta 0:00:07
     --------- ---------------------------- 30.7/119.6 kB 13.9 kB/s eta 0:00:07
     --------- ---------------------------- 30.7/119.6 kB 13.9 kB/s eta 0:00:07
     --------- ---------------------------- 30.7/119.6 kB 13.9 kB/s eta 0:00:07
     --------- ---------------------------- 30.7/119.6 kB 13.9 kB/s eta 0:00:07
     --------- ---------------------------- 30.7/119.6 kB 13.9 kB/s eta 0:00:07
     --------- ---------------------------- 30.7/119.6 kB 13.9 kB/s eta 0:00:07
     --------- ---------------------------- 30.7/119.6 kB 13.9 kB/s eta 0:00:07
     --------- ---------------------------- 30.7/119.6 kB 13.9 kB/s eta 0:00:07
     --------- ---------------------------- 30.7/119.6 kB 13.9 kB/s eta 0:00:07
     --------- ---------------------------- 30.7/119.6 kB 13.9 kB/s eta 0:00:07
     --------- ---------------------------- 30.7/119.6 kB 13.9 kB/s eta 0:00:07
     --------- ---------------------------- 30.7/119.6 kB 13.9 kB/s eta 0:00:07
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------- ------------------------ 41.0/119.6 kB 14.4 kB/s eta 0:00:06
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     ------------------- ------------------ 61.4/119.6 kB 14.2 kB/s eta 0:00:05
     -------------------------- ----------- 81.9/119.6 kB 13.6 kB/s eta 0:00:03
     -------------------------- ----------- 81.9/119.6 kB 13.6 kB/s eta 0:00:03
     -------------------------- ----------- 81.9/119.6 kB 13.6 kB/s eta 0:00:03
     -------------------------- ----------- 81.9/119.6 kB 13.6 kB/s eta 0:00:03
     -------------------------- ----------- 81.9/119.6 kB 13.6 kB/s eta 0:00:03
     -------------------------- ----------- 81.9/119.6 kB 13.6 kB/s eta 0:00:03
     -------------------------- ----------- 81.9/119.6 kB 13.6 kB/s eta 0:00:03
     -------------------------- ----------- 81.9/119.6 kB 13.6 kB/s eta 0:00:03
     -------------------------- ----------- 81.9/119.6 kB 13.6 kB/s eta 0:00:03
     -------------------------- ----------- 81.9/119.6 kB 13.6 kB/s eta 0:00:03
     -------------------------- ----------- 81.9/119.6 kB 13.6 kB/s eta 0:00:03
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ----------------------------- -------- 92.2/119.6 kB 14.2 kB/s eta 0:00:02
     ---------------------------------- -- 112.6/119.6 kB 15.3 kB/s eta 0:00:01
     ------------------------------------- 119.6/119.6 kB 16.3 kB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading kiwisolver-1.5.0-cp311-cp311-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Collecting pyparsing>=3 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading matplotlib-3.10.8-cp311-cp311-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB 34.5 kB/s eta 0:03:56
   ---------------------------------------- 0.0/8.1 MB 34.5 kB/s eta 0:03:56
   ---------------------------------------- 0.0/8.1 MB 34.5 kB/s eta 0:03:56
   ---------------------------------------- 0.0/8.1 MB 34.5 kB/s eta 0:03:56
   ---------------------------------------- 0.0/8.1 MB 34.5 kB/s eta 0:03:56

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
!pip install seaborn

Requirement already satisfied: seaborn in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (2.3.5)
Requirement already satisfied: pandas>=1.2 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (3.0.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
import seaborn as sns

In [8]:
!pip install pandas numpy matplotlib seaborn

Requirement already satisfied: pandas in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (3.0.1)
Requirement already satisfied: numpy in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (2.3.5)
Requirement already satisfied: matplotlib in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (3.10.8)
Requirement already satisfied: seaborn in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os
os.listdir()

['-1.14-windows.xml',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.mobisystems',
 '.ms-ad',
 '.node_repl_history',
 '.th-client',
 '.vscode',
 '3D Objects',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'HTML TUTORIAL',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'Microsoft',
 'Music',
 'My Documents',
 'NetHood',
 'node_modules',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{6adba09c-20f8-11f0-8dc1-b0dbf0dde211}.TM.blf',
 'NTUSER.DAT{6adba09c-20f8-11f0-8dc1-b0dbf0dde211}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{6adba09c-20f8-11f0-8dc1-b0dbf0dde211}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'package-lock.json',
 'package.json',
 'Pictures',
 'PrintHood',
 'PyCharmMiscProject',
 'PycharmProjects',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'shopping_behavior_ll (1).csv.ipynb',
 'shopping_behavior_updated (1).csv',
 'shopping_behavior_updated (1).csv.ipynb',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'untitled.py',
 'Untitled1.ipynb',
 'untitled1.py',
 'Untitled2.ipynb',
 'untitled2.py',
 'Untitled3.ipynb',
 'Videos']

In [3]:
import pandas as pd

df = pd.read_csv("shopping_behavior_updated (1).csv")
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Yes,31,PayPal,Annually

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3900 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Discount Applied        3900 non-null   str
 13  Previous Purchases      3900 non-null   int64
 14  Payment Method          3900 non-null   str
 15  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(11)
memory usage: 723.8 KB

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.749949,25.351538
std,1125.977353,15.207589,23.685392,0.716223,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.700000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [7]:
print(df.columns)

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Discount Applied',
       'Previous Purchases', 'Payment Method', 'Frequency of Purchases'],
      dtype='str')

In [22]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [24]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       '_purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'discount_applied',
       'previous_purchases', 'payment_method', 'frequency_of_purchases',
       'age_group', 'purchase_frequency_days'],
      dtype='str')

In [25]:
#create a new column age_group 
labels=['young adult', 'adult', 'middle aged','senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [26]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55  middle aged
1   19  young adult
2   50  middle aged
3   21  young adult
4   45  middle aged
5   46  middle aged
6   63       senior
7   27  young adult
8   26  young adult
9   57  middle aged

In [27]:
df['frequency_of_purchases'] = df['frequency_of_purchases'].str.strip().str.lower()

In [28]:
# create column purchase_frequency_days 
frequency_map = {
    'fortnightly': 14,
    'weekly': 7,
    'monthly': 30,
    'quarterly': 90,
    'bi-weekly': 14,
    'annually': 365,
    'every 3 months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_map)

In [29]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            fortnightly
1                       14            fortnightly
2                        7                 weekly
3                        7                 weekly
4                      365               annually
5                        7                 weekly
6                       90              quarterly
7                        7                 weekly
8                      365               annually
9                       90              quarterly

In [32]:
df[['_purchase_amount','discount_applied']].head(10)

   _purchase_amount discount_applied
0                53              Yes
1                64              Yes
2                73              Yes
3                90              Yes
4                49              Yes
5                20              Yes
6                85              Yes
7                34              Yes
8                97              Yes
9                31              Yes

In [34]:
(df['_purchase_amount'] == df['discount_applied']).all()

np.False_

In [17]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (1.1.2)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [31]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

#step 1: connect to postgresql
#replace placeholders with your actual details 
username = "root"   #default user
password = quote_plus("Sedi@123")  #PASS that created by me
host = "localhost"       #if running locally
port = "3306"             # default postgreSQL port
database = "customer_behaviour"  # the database created in pgadmin

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

#step 2: load dataframe into MYSQL 
table_name = "customer" # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"data successfully loaded into table '{table_name}' in database '{database}'.")

data successfully loaded into table 'customer' in database 'customer_behaviour'.